# Quantumult X 91直播“查房发包模板”跨端抓取重写规则

hostname = kex.aynjxxw.com, jgm.opuxrcm.com

# 精准狙击获取全部房间列表的鉴权模板，并截取 Request Body
^https?:\/\/(kex\.aynjxxw\.com|jgm\.opuxrcm\.com)\/room\/recommend\/anchor\/list url script-request-body https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/91live_template_hunter.js
