# Quantumult X 91直播“查房发包模板”跨端抓取重写规则

hostname = kex.aynjxxw.com, jgm.opuxrcm.com

# 拦截该域名下任何被加密保护的路径请求，并统一交由电脑端去实施解密剥离推荐查壳
^https?:\/\/(kex\.aynjxxw\.com|jgm\.opuxrcm\.com)\/.* url script-request-body https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/91live_template_hunter.js
