# Quantumult X live stream capture rules - Mobile network ntfy relay edition

hostname = *.szier2.com, *.sourcelandchina.com, *.hwcloudlive.com, log-collection-new.hwcloudlive.com

^https?:\/\/.*\.hwcloudlive\.com\/v2\/log\/log_report url script-request-body https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/fanqie_mobile_ntfy_private.js?v=20260311b
^https?:\/\/.*\.szier2\.com\/live\/.* url script-request-header https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/fanqie_mobile_ntfy_private.js?v=20260311b
^https?:\/\/.*\.sourcelandchina\.com\/live\/.* url script-request-header https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/fanqie_mobile_ntfy_private.js?v=20260311b
