hostname = *.szier2.com, *.sourcelandchina.com, hls-cdn.hwcloudlive.com

# Quantumult X 直播源抓取配置 (v6.8 强制刷新版)
# 💡 v6.8 升级：强制指向新命名的 v6_4.js，彻底粉碎旧缓存！

^https?:\/\/hls-cdn\.hwcloudlive\.com\/.*log_report url script-request-body https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/fanqie_detector_v6_4.js
^https?:\/\/.*\.szier2\.com\/live\/.* url script-request-header https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/fanqie_detector_v6_4.js
^https?:\/\/.*\.sourcelandchina\.com\/live\/.* url script-request-header https://raw.githubusercontent.com/nikiat12-source/quantumultx-scripts/main/fanqie_detector_v6_4.js
